name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-app:latest

  scan:
    name: Scan image for vulnerabilities
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Scout CVEs
        uses: docker/scout-action@v1.5.0
        with:
          command: cves
          image: ${{ secrets.DOCKERHUB_USERNAME }}/student-app:latest
          # only-severities: critical,high # Schakel deze regel in/uit voor de opdracht
          exit-code: true
          ignore-cves: CVE-2023-25577,CVE-2025-59375,CVE-2023-30861
        
  test:
    name: Test
    needs: [scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run container and perform a basic test
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/student-app:latest
          docker run -d --name student-app-test -p 8080:5000 ${{ secrets.DOCKERHUB_USERNAME }}/student-app:latest
          
          echo "Wachten op de applicatie..."
          timeout=60
          while ! curl -s --fail http://localhost:8080 > /dev/null; do
            timeout=$((timeout - 5))
            if [ $timeout -le 0 ]; then
              echo "Applicatie startte niet op tijd."
              docker logs student-app-test
              exit 1
            fi
            sleep 5
          done
          
          echo "Applicatie is online! Test wordt uitgevoerd."
          curl http://localhost:8080
          docker stop student-app-test

  deploy:
    name: Deploy
    needs: [test]
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Deploy to Kubernetes
        run: |
          sudo k3s kubectl apply -f ${{ github.workspace }}/kubernetes/deployment.yaml
          sudo k3s kubectl apply -f ${{ github.workspace }}/kubernetes/nginx-service.yaml
          sudo k3s kubectl rollout restart deployment student-devsecops

  postman_api_tests:
    name: Run Postman API Tests
    needs: [deploy] # Draait pas nadat de 'deploy' job succesvol is
    runs-on: ubuntu-latest
    steps:
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests on deployed application
        run: |
          postman collection run "28818015-b9e509f7-7dd9-4619-af1e-f847180d7ced" --env-var "baseUrl=http://${{ secrets.PUBLIC_IP }}:30000"
